_BATCH_ACCOUNT_NAME ='<TO_BE_FILLED>'
_BATCH_ACCOUNT_KEY = '<TO_BE_FILLED>'
_BATCH_ACCOUNT_URL = '<TO_BE_FILLED>'

_INPUT_CONTAINER_URL = '<TO_BE_FILLED>'
_OUTPUT_CONTAINER_URL = '<TO_BE_FILLED>'
_JAR_CONTAINER = 'fgrp-sequencer-code'
_JAR_FILE = 'sequencefiletransformer-0.0.1-SNAPSHOT.jar'

_POOL_VM_SIZE = 'STANDARD_H16'
_MAX_NODES = 5
_TASKS_PER_NODE = 8

